// server/engine/catalog/fallbacks.js
// One broadly applicable niche per archetype. The engine uses these when a
// prompt is too vague to match a specific niche ("an online store", "my
// business", "my portfolio"). Keywords are deliberately generic.

export default [
  {
    id: "general-store",
    name: "Online Store",
    group: "retail",
    archetype: "store",
    keywords: ["online store", "ecommerce", "e-commerce", "shop", "store", "online shop", "sell product", "product", "products", "dropshipping", "d2c", "dtc brand", "webshop", "web shop", "shopping site", "sell online", "online business", "merchandise", "goods", "shopify store", "retail brand"],
    mood: ["clean", "minimal", "warm"],
    images: "shop",
    copy: {
      brand: "Northwind Goods",
      label: "THOUGHTFULLY MADE GOODS",
      heading: "Everyday things, made to be kept",
      sub: "Small-batch essentials for home and daily life, chosen for how they are made and built to outlast the season.",
      cta1: "Shop the Collection",
      cta2: "Read Our Story",
      offerings: {
        label: "WHY SHOP WITH US",
        heading: "Better goods, fewer compromises",
        sub: "Every product earns its place through honest materials, careful craft and everyday usefulness.",
        items: [
          { title: "Carefully Sourced", desc: "We work directly with small makers and visit their workshops before anything reaches our shelves.", icon: "🧵" },
          { title: "Free Shipping Over $60", desc: "Orders over $60 ship free, packed in recycled boxes with no single-use plastic inside.", icon: "📦" },
          { title: "30-Day Returns", desc: "Changed your mind? Send it back within 30 days for a full refund, no questions asked.", icon: "🔄" },
          { title: "Secure Checkout", desc: "Pay by card, wallet or bank transfer through an encrypted checkout that never stores your details.", icon: "🔒" },
          { title: "Made to Last", desc: "Durable materials and honest construction, backed by a one-year guarantee on every item.", icon: "🛠" },
          { title: "Real Human Support", desc: "Questions about sizing, care or delivery? Our small team replies within one business day.", icon: "💬" },
        ],
      },
      showcase: {
        label: "BESTSELLERS",
        heading: "Customer favorites this season",
        items: [
          { name: "Stoneware Coffee Mug", meta: "$28", details: "Hand-glazed, 350 ml, dishwasher safe" },
          { name: "Amber Soy Candle", meta: "$34", details: "Cedar and fig, 50-hour burn, reusable glass jar" },
          { name: "Canvas Market Tote", meta: "$42", details: "Heavy organic cotton with reinforced handles" },
          { name: "Wireless Headphones", meta: "$129", details: "40-hour battery, soft memory-foam cushions" },
          { name: "Ceramic Plant Pot", meta: "$36", details: "Matte glaze, drainage hole, fits 12 cm plants" },
          { name: "Instant Camera", meta: "$149", details: "Prints in seconds, starter film pack included" },
        ],
      },
      stats: [
        { num: "12K+", label: "Orders Shipped" },
        { num: "4.8", label: "Average Rating" },
        { num: "60+", label: "Independent Makers" },
        { num: "30 days", label: "Free Returns" },
      ],
      about: {
        label: "OUR STORY",
        heading: "A small shop with high standards",
        body1: "Northwind Goods started with a simple frustration: too many everyday products were built to be replaced. We set out to find the ones worth keeping, from the mug you reach for every morning to the bag you carry for years.",
        body2: "Today we partner with more than sixty independent makers. We test every item at home before listing it, keep our range deliberately small and share exactly where and how each piece is made.",
      },
      testimonials: {
        label: "CUSTOMER REVIEWS",
        heading: "Loved in homes everywhere",
        items: [
          { quote: "The mug is now the one everyone in my house fights over. It arrived beautifully packed, two days after I ordered.", name: "Hannah Okafor", role: "Verified Buyer" },
          { quote: "I returned a tote in the wrong color and had my refund within a week. Easy, friendly and genuinely no fuss.", name: "Daniel Reyes", role: "Repeat Customer" },
          { quote: "Thoughtful products and honest descriptions. What you see on the page is exactly what turns up at your door.", name: "Priya Nair", role: "Interior Stylist" },
        ],
      },
      faq: {
        label: "COMMON QUESTIONS",
        heading: "Before you place an order",
        items: [
          { q: "How long does delivery take?", a: "Most orders are packed within one business day and arrive in 2 to 5 business days. You will receive tracking as soon as your parcel leaves us." },
          { q: "Do you ship internationally?", a: "Yes, we ship to more than 30 countries. Shipping costs and any import duties are shown at checkout before you pay." },
          { q: "What is your return policy?", a: "Unused items can be returned within 30 days for a full refund. Start a return from the link in your order confirmation email." },
          { q: "Are your products sustainably made?", a: "We favor natural and recycled materials, and we list the origin and materials of every product on its page." },
        ],
      },
      cta: {
        heading: "Find something worth keeping",
        sub: "Browse the full collection and enjoy free shipping on every order over $60.",
        button: "Shop Now",
      },
      seo: {
        title: "Northwind Goods – Thoughtfully Made Everyday Goods",
        description: "Shop small-batch home and lifestyle essentials from independent makers. Free shipping over $60, 30-day returns and secure checkout.",
      },
    },
  },

  {
    id: "general-restaurant",
    name: "Neighborhood Restaurant",
    group: "food",
    archetype: "restaurant",
    keywords: ["restaurant", "eatery", "diner", "food place", "dining", "dine in", "eating place", "food joint", "kitchen", "menu", "lunch", "dinner", "brunch", "cuisine", "family restaurant", "casual dining", "takeaway", "table booking", "reservation", "chef", "food business", "local restaurant"],
    mood: ["warm", "elegant"],
    images: "restaurant",
    copy: {
      brand: "The Copper Table",
      label: "SEASONAL KITCHEN & BAR",
      heading: "Seasonal plates worth coming back for",
      sub: "A relaxed neighborhood kitchen serving fresh, seasonal dishes from brunch to late dinner, with a warm welcome at every table.",
      cta1: "Reserve a Table",
      cta2: "View the Menu",
      offerings: {
        label: "THE EXPERIENCE",
        heading: "More than just a meal",
        sub: "Fresh ingredients, a friendly room and service that remembers your name.",
        items: [
          { title: "Seasonal Menu", desc: "Our chefs rewrite the menu with the seasons, working closely with local farms and producers.", icon: "🥗" },
          { title: "Wood-Fired Oven", desc: "Breads, pizzas and roasted vegetables cooked over real fire for deep, smoky flavor.", icon: "🔥" },
          { title: "Private Dining", desc: "A private room for up to 24 guests, ideal for birthdays, team dinners and celebrations.", icon: "🥂" },
          { title: "Takeaway & Delivery", desc: "Order your favorites online for pickup or delivery, packed to arrive hot and fresh.", icon: "🛵" },
          { title: "Dietary Friendly", desc: "Vegetarian, vegan and gluten-free dishes clearly marked, with swaps available on request.", icon: "🌿" },
          { title: "Weekend Brunch", desc: "Slow Saturday and Sunday mornings with fresh pastries, good coffee and pressed juices.", icon: "☕" },
        ],
      },
      showcase: {
        label: "SIGNATURE DISHES",
        heading: "What our regulars order",
        items: [
          { name: "Steak Frites", meta: "$28", details: "Grass-fed sirloin, hand-cut fries, herb butter" },
          { name: "Wood-Fired Margherita", meta: "$16", details: "San Marzano tomato, fresh mozzarella, basil" },
          { name: "Garden Grain Bowl", meta: "$14", details: "Quinoa, roasted vegetables, soft egg, tahini" },
          { name: "Chef's Tasting Plate", meta: "$32", details: "Five small courses that change every week" },
          { name: "Spiced Beef Salad", meta: "$18", details: "Chili, lime, fresh herbs and toasted cashews" },
        ],
      },
      stats: [
        { num: "15", label: "Years Cooking Here" },
        { num: "120", label: "Seats Indoors & Out" },
        { num: "4.7", label: "Guest Rating" },
        { num: "30+", label: "Local Suppliers" },
      ],
      about: {
        label: "OUR STORY",
        heading: "A kitchen built around the neighborhood",
        body1: "The Copper Table opened as a small corner kitchen with twelve seats and one simple idea: cook the kind of food we love to eat, using ingredients from people we know by name.",
        body2: "The room is bigger now, but the approach is the same. Bread is baked every morning, sauces are made from scratch and the menu follows whatever is best at the market that week.",
      },
      testimonials: {
        label: "GUEST REVIEWS",
        heading: "What our guests are saying",
        items: [
          { quote: "Our go-to spot for family dinners. The staff know our order, the kids love the pizza and the steak is excellent.", name: "Marco Bianchi", role: "Regular Guest" },
          { quote: "We booked the private room for a team dinner and everything, from the menu to the service, was handled perfectly.", name: "Aisha Rahman", role: "Operations Manager" },
          { quote: "Weekend brunch here has become a ritual. Great coffee, generous plates and a room that always feels relaxed.", name: "Liam O'Connor", role: "Local Resident" },
        ],
      },
      faq: {
        label: "GOOD TO KNOW",
        heading: "Planning your visit",
        items: [
          { q: "Do I need a reservation?", a: "Walk-ins are always welcome, but we recommend booking for dinner on Fridays and weekends, when tables fill quickly." },
          { q: "Do you cater to dietary requirements?", a: "Yes. Vegetarian, vegan and gluten-free dishes are marked on the menu, and our kitchen will happily adapt most plates." },
          { q: "Can I book for a large group?", a: "Groups of up to 24 can reserve our private dining room. Get in touch and we will help plan a set menu for your occasion." },
          { q: "Do you offer takeaway?", a: "Most of the menu is available for pickup or delivery. Order online or call us directly during opening hours." },
        ],
      },
      cta: {
        heading: "Your table is waiting",
        sub: "Book online in under a minute, or drop by for a relaxed meal tonight.",
        button: "Book a Table",
      },
      seo: {
        title: "The Copper Table – Seasonal Neighborhood Restaurant",
        description: "Fresh seasonal dishes, wood-fired pizza and weekend brunch in a warm neighborhood setting. Reserve a table or order takeaway online.",
      },
    },
  },

  {
    id: "general-saas",
    name: "Software Product",
    group: "tech",
    archetype: "saas",
    keywords: ["saas", "software", "app", "platform", "tool", "startup", "web app", "mobile app", "software product", "tech startup", "product launch", "subscription software", "cloud software", "b2b software", "application", "digital product", "api", "automation tool", "productivity tool", "dashboard"],
    mood: ["clean", "tech", "minimal"],
    images: "saas",
    copy: {
      brand: "Flowbase",
      label: "BUILT FOR MODERN TEAMS",
      heading: "Do more work with less busywork",
      sub: "Flowbase brings your projects, data and conversations into one fast workspace, so your team spends time on progress instead of updates.",
      cta1: "Start Free Trial",
      cta2: "Book a Demo",
      offerings: {
        label: "PLATFORM FEATURES",
        heading: "Everything your team needs in one place",
        sub: "Powerful enough for growing companies, simple enough to set up in an afternoon.",
        items: [
          { title: "Smart Automations", desc: "Turn repetitive steps into rules that run in the background, from reminders to approvals.", icon: "⚡" },
          { title: "Real-Time Dashboards", desc: "See progress, workload and key metrics update live without building a single spreadsheet.", icon: "📊" },
          { title: "100+ Integrations", desc: "Connect the tools you already use, including email, calendars, file storage and payments.", icon: "🔌" },
          { title: "Team Collaboration", desc: "Comment, assign and share files right where the work happens, without endless threads.", icon: "👥" },
          { title: "Enterprise Security", desc: "Encryption at rest and in transit, single sign-on and granular permissions you control.", icon: "🛡" },
          { title: "Fast Onboarding", desc: "Import existing data in minutes and use ready-made templates to get going on day one.", icon: "🚀" },
        ],
      },
      pricing: {
        label: "SIMPLE PRICING",
        heading: "Plans that grow with you",
        plans: [
          { plan: "Starter", price: "$0", period: "/month", desc: "For individuals and small projects getting started.", features: ["Up to 3 projects", "Core automations", "Community support"] },
          { plan: "Team", price: "$12", period: "/user", desc: "For growing teams that need more power and visibility.", features: ["Unlimited projects", "Advanced dashboards", "100+ integrations", "Priority email support"] },
          { plan: "Business", price: "$29", period: "/user", desc: "Security, controls and support for larger organizations.", features: ["Single sign-on", "Granular permissions", "Audit logs", "Dedicated success manager"] },
        ],
      },
      stats: [
        { num: "10K+", label: "Teams Onboard" },
        { num: "99.9%", label: "Uptime" },
        { num: "8 hrs", label: "Saved Per Week" },
        { num: "4.8/5", label: "Customer Rating" },
      ],
      about: {
        label: "WHY WE BUILT IT",
        heading: "Software that gets out of your way",
        body1: "Flowbase began inside a small product team that was spending more time updating tools than doing the actual work. So we built the workspace we wanted: fast, focused and easy for everyone to adopt.",
        body2: "Today thousands of teams use Flowbase to plan, track and ship their work. We release improvements every week, and every new feature starts with a conversation with our customers.",
      },
      testimonials: {
        label: "CUSTOMER STORIES",
        heading: "Teams that switched never looked back",
        items: [
          { quote: "We replaced three separate tools with Flowbase and cut our weekly status meeting in half within the first month.", name: "Sofia Lindqvist", role: "Head of Operations" },
          { quote: "Setup took one afternoon. The automations alone save our support team hours of manual follow-up every week.", name: "Kwame Mensah", role: "Customer Support Lead" },
          { quote: "Finally, a dashboard our leadership actually opens. Everyone sees the same numbers, updated in real time.", name: "Emily Chen", role: "Product Director" },
        ],
      },
      faq: {
        label: "COMMON QUESTIONS",
        heading: "Everything you need to know",
        items: [
          { q: "Is there a free trial?", a: "Yes. Every paid plan includes a 14-day free trial with full features, and no credit card is required to start." },
          { q: "Can I import data from other tools?", a: "You can import from spreadsheets and most popular project tools in a few clicks, and our team can help with larger migrations." },
          { q: "How secure is my data?", a: "Data is encrypted in transit and at rest, backed up daily and hosted in certified data centers with strict access controls." },
          { q: "Can I change or cancel my plan?", a: "Upgrade, downgrade or cancel at any time from your account settings. Changes apply from your next billing cycle." },
        ],
      },
      cta: {
        heading: "Start building a calmer workflow today",
        sub: "Try every feature free for 14 days. Set up in minutes, no credit card required.",
        button: "Start Free Trial",
      },
      seo: {
        title: "Flowbase – Work Management Software for Modern Teams",
        description: "Plan projects, automate busywork and track progress in real time. Flowbase connects your team and tools in one workspace. Start free.",
      },
    },
  },

  {
    id: "general-agency",
    name: "Creative Agency",
    group: "business",
    archetype: "agency",
    keywords: ["agency", "studio", "consultancy", "creative agency", "design agency", "digital agency", "creative studio", "design studio", "consulting", "consultant", "professional services", "advertising", "brand strategy", "branding", "full service agency", "agency website"],
    mood: ["bold", "editorial", "clean"],
    images: "business",
    copy: {
      brand: "Northwind Studio",
      label: "STRATEGY, DESIGN & GROWTH",
      heading: "We build brands people remember",
      sub: "An independent studio helping ambitious companies sharpen their story, design standout experiences and grow with measurable results.",
      cta1: "Start a Project",
      cta2: "See Our Work",
      offerings: {
        label: "WHAT WE DO",
        heading: "Services built around your goals",
        sub: "Senior specialists in strategy, design and marketing, working as one team.",
        items: [
          { title: "Brand Strategy", desc: "Research, positioning and messaging that give your business a clear, confident voice.", icon: "🧭" },
          { title: "Visual Identity", desc: "Logos, typography and design systems that stay consistent across every touchpoint.", icon: "🎨" },
          { title: "Websites & Apps", desc: "Fast, accessible digital products that convert visitors and are easy for your team to update.", icon: "💻" },
          { title: "Content & Campaigns", desc: "Photography, video and campaign ideas that turn attention into lasting interest.", icon: "🎬" },
          { title: "Growth Marketing", desc: "Search, social and paid media planned around data and measured against real business outcomes.", icon: "📈" },
          { title: "Ongoing Partnership", desc: "A dedicated team on retainer for launches, experiments and everyday creative support.", icon: "🤝" },
        ],
      },
      team: {
        label: "MEET THE TEAM",
        heading: "The people behind the work",
        items: [
          { name: "Olivia Hart", title: "Founder & Creative Director", bio: "Fifteen years leading brand and digital work for startups, cultural institutions and global names." },
          { name: "Rahul Mehta", title: "Head of Strategy", bio: "Turns research and data into clear positioning and plans that teams can act on." },
          { name: "Chloe Dubois", title: "Design Lead", bio: "Crafts identities and interfaces with a sharp eye for type, color and detail." },
        ],
      },
      pricing: {
        label: "WAYS TO WORK",
        heading: "Engagements that fit your stage",
        plans: [
          { plan: "Sprint", price: "$4,500", desc: "A focused two-week project for one clear challenge.", features: ["Discovery workshop", "One core deliverable", "Two rounds of revisions"] },
          { plan: "Project", price: "$15,000", desc: "A complete brand or website project, start to finish.", features: ["Research and strategy", "Full design system", "Build and launch support", "Dedicated project lead"] },
          { plan: "Retainer", price: "$6,000", period: "/month", desc: "An embedded creative team for continuous work.", features: ["Monthly strategy sessions", "Design and content output", "Performance reporting", "Priority turnaround"] },
        ],
      },
      stats: [
        { num: "120+", label: "Projects Delivered" },
        { num: "12", label: "Years in Business" },
        { num: "92%", label: "Clients Who Return" },
        { num: "18", label: "Design Awards" },
      ],
      about: {
        label: "ABOUT THE STUDIO",
        heading: "Small team, senior thinking, real outcomes",
        body1: "Northwind Studio was founded on the belief that great work comes from small, senior teams who stay close to the problem. No hand-offs to juniors and no layers of account management, just direct collaboration.",
        body2: "We have partnered with startups, established brands and nonprofits across more than forty industries. Every engagement starts with listening and ends with work we can measure.",
      },
      testimonials: {
        label: "CLIENT FEEDBACK",
        heading: "Trusted by teams that care about craft",
        items: [
          { quote: "They understood our business in weeks, not months. The new brand gave our sales team something they are proud to show.", name: "James Whitaker", role: "CEO, Fieldstone Logistics" },
          { quote: "Our redesigned site doubled demo requests in the first quarter. Clear process, great communication, zero surprises.", name: "Ana Souza", role: "Marketing Director" },
          { quote: "It felt like an extension of our own team. Thoughtful, fast and honest whenever something was not working.", name: "Yuki Tanaka", role: "Founder, Kiko Skincare" },
        ],
      },
      faq: {
        label: "COMMON QUESTIONS",
        heading: "Working with us",
        items: [
          { q: "What size of companies do you work with?", a: "Mostly startups and mid-sized businesses, along with larger organizations that want a nimble, senior team." },
          { q: "How long does a typical project take?", a: "Brand projects usually take 6 to 10 weeks and websites 8 to 12 weeks, depending on scope and how quickly feedback moves." },
          { q: "How do you price your work?", a: "We quote a fixed fee for defined projects and a monthly rate for retainers, agreed upfront so there are no surprises." },
          { q: "Can you work alongside our in-house team?", a: "Absolutely. We regularly collaborate with internal marketing, product and engineering teams and hand over everything we create." },
        ],
      },
      cta: {
        heading: "Have a project in mind?",
        sub: "Tell us where you want to go. We reply within two business days with clear next steps.",
        button: "Start a Project",
      },
      seo: {
        title: "Northwind Studio – Brand Strategy, Design & Digital",
        description: "An independent creative studio for brand strategy, visual identity, websites and growth marketing. See our work and start a project today.",
      },
    },
  },

  {
    id: "general-local-business",
    name: "Local Business",
    group: "services",
    archetype: "local",
    keywords: ["business", "company", "small business", "firm", "services", "local business", "enterprise", "local company", "service provider", "business website", "professional services", "local firm", "family business", "established business", "local services", "business owner"],
    mood: ["clean", "corporate", "warm"],
    images: "business",
    copy: {
      brand: "Bridgeport & Co",
      label: "TRUSTED LOCAL BUSINESS",
      heading: "Reliable service, right in your neighborhood",
      sub: "A local team that shows up on time, communicates clearly and stands behind every job, big or small.",
      cta1: "Get a Quote",
      cta2: "Our Services",
      offerings: {
        label: "WHAT WE OFFER",
        heading: "Support at every stage of your project",
        sub: "From the first call to the final walkthrough, we keep you informed and on schedule.",
        items: [
          { title: "Free Consultations", desc: "Tell us what you need and we'll outline options, timelines and costs before anything is booked.", icon: "📋" },
          { title: "Licensed & Insured", desc: "Every job is carried out by fully licensed, insured staff who follow local codes and safety rules.", icon: "✅" },
          { title: "Transparent Pricing", desc: "Written quotes with no hidden fees, so you know the full cost before we start any work.", icon: "💲" },
          { title: "On-Time Arrival", desc: "We schedule a clear window and call ahead, so your day is not spent waiting around.", icon: "⏰" },
          { title: "Satisfaction Guarantee", desc: "If something is not right, we return and fix it at no extra charge until you are happy.", icon: "🤝" },
          { title: "Emergency Support", desc: "Urgent issue? Our team takes emergency calls and can often be on site the same day.", icon: "🚨" },
        ],
      },
      team: {
        label: "MEET THE TEAM",
        heading: "The people who do the work",
        items: [
          { name: "Marcus Bell", title: "Owner & Operations Lead", bio: "Started the business in a single van and now oversees every project from quote to completion." },
          { name: "Renee Castillo", title: "Customer Success Manager", bio: "Your first call and main point of contact, keeping every job on schedule and on budget." },
          { name: "Devon Ashworth", title: "Senior Technician", bio: "Over a decade of hands-on experience, training every new technician who joins the team." },
        ],
      },
      pricing: {
        label: "SERVICE PACKAGES",
        heading: "Choose the level of support you need",
        plans: [
          { plan: "Basic", price: "$89", period: "/visit", desc: "A single scheduled visit for routine work or a quick fix.", features: ["One service call", "Written estimate", "30-day workmanship guarantee"] },
          { plan: "Standard", price: "$249", period: "/month", desc: "Regular scheduled visits with priority booking.", features: ["Monthly visit", "Priority scheduling", "Discounted parts", "Phone support"] },
          { plan: "Premium", price: "$499", period: "/month", desc: "Fastest response and full coverage for busy sites.", features: ["Two visits monthly", "Same-day emergency slot", "Priority parts sourcing", "Dedicated account manager"] },
        ],
      },
      stats: [
        { num: "18+", label: "Years in Business" },
        { num: "6,200+", label: "Jobs Completed" },
        { num: "4.9", label: "Average Rating" },
        { num: "24/7", label: "Emergency Support" },
      ],
      about: {
        label: "OUR STORY",
        heading: "Built on reliability, one job at a time",
        body1: "Bridgeport & Co started in 2008 with one technician, one van and a promise to always call back. That promise is still how we run the business today.",
        body2: "We have since grown into a full team covering the greater metro area, but we still take every job personally and stand behind the work with a written guarantee.",
      },
      testimonials: {
        label: "WHAT CLIENTS SAY",
        heading: "Trusted by homes and businesses nearby",
        items: [
          { quote: "They arrived exactly when promised and explained everything before starting. No surprises on the bill either.", name: "Grace Whitfield", role: "Homeowner" },
          { quote: "We use them for all our office maintenance now. Responsive, fair pricing and the work always holds up.", name: "Tomas Novak", role: "Facilities Manager" },
          { quote: "Called with an emergency on a Sunday and someone was here within two hours. Genuinely impressed.", name: "Layla Haddad", role: "Property Owner" },
        ],
      },
      faq: {
        label: "COMMON QUESTIONS",
        heading: "What to expect when you book",
        items: [
          { q: "How quickly can you come out?", a: "Standard bookings are typically scheduled within 2 to 3 business days, and emergency requests are often handled the same day." },
          { q: "Are your technicians licensed?", a: "Yes, every technician is fully licensed, insured and background checked before joining the team." },
          { q: "Do you offer free estimates?", a: "Yes, we provide a written estimate before any work begins, with no obligation to proceed." },
          { q: "What areas do you serve?", a: "We cover the greater metro area and surrounding towns within roughly 30 miles of downtown." },
        ],
      },
      cta: {
        heading: "Ready to get started?",
        sub: "Request a free quote today and hear back from our team within one business day.",
        button: "Get a Quote",
      },
      seo: {
        title: "Bridgeport & Co – Trusted Local Business Services",
        description: "Licensed, insured and locally owned. Get transparent pricing, on-time arrival and a satisfaction guarantee on every job. Request a free quote today.",
      },
    },
  },

  {
    id: "general-portfolio",
    name: "Personal Portfolio",
    group: "personal",
    archetype: "portfolio",
    keywords: ["portfolio", "personal website", "personal site", "resume website", "cv website", "about me", "my work", "personal portfolio", "online resume", "personal page", "showcase my work", "my portfolio site"],
    mood: ["minimal", "clean", "editorial"],
    images: "freelancer",
    copy: {
      brand: "Alex Morgan",
      label: "PORTFOLIO & SELECTED WORK",
      heading: "Hi, I'm Alex — I build things and tell their story",
      sub: "A running record of projects, experiments and the work I'm proud to put my name on, updated as I go.",
      cta1: "View My Work",
      cta2: "Get in Touch",
      offerings: {
        label: "WHAT I DO",
        heading: "A few things I bring to every project",
        sub: "Skills and habits I rely on, from the first sketch to the final handoff.",
        items: [
          { title: "Project Planning", desc: "Breaking a vague idea into a clear scope, timeline and set of milestones everyone can follow.", icon: "🗂" },
          { title: "Hands-On Execution", desc: "Comfortable doing the actual work myself, not just directing it from a distance.", icon: "🛠" },
          { title: "Clear Communication", desc: "Regular updates and honest timelines, so there are never any surprises along the way.", icon: "💬" },
          { title: "Attention to Detail", desc: "The small choices, spacing, wording, timing, are the ones I care about most.", icon: "🔍" },
          { title: "Fast Iteration", desc: "I would rather ship a rough version and improve it than wait for a perfect first draft.", icon: "⚡" },
          { title: "Reliable Follow-Through", desc: "Every project I start, I finish, and I stick around after launch to fix what comes up.", icon: "✅" },
        ],
      },
      showcase: {
        label: "SELECTED WORK",
        heading: "A few projects worth a closer look",
        items: [
          { name: "Meridian Rebrand", meta: "2024", details: "Full visual identity and website for a growing consultancy" },
          { name: "Riverside App", meta: "Case Study", details: "Designed and built a booking flow used by 8,000+ customers" },
          { name: "Fieldnotes Newsletter", meta: "2023", details: "Grew a weekly newsletter from zero to 12,000 subscribers" },
          { name: "Launch Sprint", meta: "2023", details: "Led a five-day sprint that shipped a client's MVP" },
          { name: "Open Roads Archive", meta: "Personal", details: "A self-directed photo and writing project on small towns" },
        ],
      },
      stats: [
        { num: "40+", label: "Projects Completed" },
        { num: "7", label: "Years of Experience" },
        { num: "15+", label: "Happy Clients" },
        { num: "3", label: "Awards & Mentions" },
      ],
      about: {
        label: "ABOUT ME",
        heading: "The short version of my story",
        body1: "I started out fixing small problems for friends and local businesses, and one project kept leading to the next. These days I split my time between client work and a few things I make just for myself.",
        body2: "I care most about the work holding up after launch, not just looking good in a screenshot. If you want to see how I think, the projects below are a fair sample.",
      },
      timeline: {
        label: "EXPERIENCE",
        heading: "How I got here",
        items: [
          { title: "Freelance Practice", desc: "Working independently with a small roster of long-term clients across industries.", year: "2022 - Now" },
          { title: "Product Studio", desc: "Worked on client projects spanning branding, web design and product strategy.", year: "2019 - 2022" },
          { title: "First Junior Role", desc: "Learned the fundamentals on a small in-house team, from brief to delivery.", year: "2017 - 2019" },
          { title: "Started Freelancing", desc: "Took on my first paid projects for friends and local businesses.", year: "2015 - 2017" },
        ],
      },
      testimonials: {
        label: "WHAT PEOPLE SAY",
        heading: "Kind words from people I've worked with",
        items: [
          { quote: "Alex is the rare person who is both a strong thinker and someone who actually ships. Every deadline was met.", name: "Priya Chandran", role: "Founder, Meridian" },
          { quote: "Clear communicator, fast turnaround and genuinely good taste. I would work together again in a heartbeat.", name: "Ben Okafor", role: "Product Lead" },
          { quote: "Took a messy brief and turned it into something better than what we asked for.", name: "Carla Jimenez", role: "Marketing Director" },
        ],
      },
      faq: {
        label: "QUESTIONS I GET",
        heading: "A few things people ask",
        items: [
          { q: "Are you available for new projects?", a: "Yes, I'm currently taking on a small number of new projects each quarter. Reach out and I'll tell you honestly if the timing works." },
          { q: "Do you work with clients remotely?", a: "Yes, most of my work is remote and I collaborate across time zones using async updates and a weekly call." },
          { q: "What is your typical rate?", a: "It depends on scope, but most engagements fall into a project-based fee agreed before work begins." },
          { q: "Can I see more examples of your work?", a: "Of course, get in touch and I'll send over a fuller portfolio relevant to what you're working on." },
        ],
      },
      cta: {
        heading: "Have a project in mind?",
        sub: "I'm always glad to hear about new ideas, even if you're not sure where to start.",
        button: "Say Hello",
      },
      seo: {
        title: "Alex Morgan – Portfolio & Selected Work",
        description: "Personal portfolio of Alex Morgan featuring selected projects, experience and client feedback across design, product and independent work.",
      },
    },
  },

  {
    id: "general-event",
    name: "Event",
    group: "events",
    archetype: "event",
    keywords: ["event", "conference", "summit", "meetup", "launch party", "event website", "gathering", "festival event", "expo", "convention", "seminar", "networking event", "event page"],
    mood: ["bold", "vibrant", "editorial"],
    images: "events",
    copy: {
      brand: "Convene Summit",
      label: "ONE DAY, ONE STAGE, BIG IDEAS",
      heading: "The event bringing your industry together",
      sub: "A full day of talks, workshops and networking designed for people who want real ideas, not just a lanyard.",
      cta1: "Get Tickets",
      cta2: "See Schedule",
      offerings: {
        label: "WHY ATTEND",
        heading: "What you'll get out of the day",
        sub: "More than a stage, this is a day built for connection and takeaways you can use.",
        items: [
          { title: "Expert Speakers", desc: "Hear from practitioners who have actually done the work, not just talked about it.", icon: "🎤" },
          { title: "Hands-On Workshops", desc: "Small-group sessions where you leave with a plan, not just notes.", icon: "📝" },
          { title: "Dedicated Networking", desc: "Structured breaks and a closing mixer designed to help you meet the right people.", icon: "🤝" },
          { title: "Curated Exhibitors", desc: "A hand-picked showroom of tools and services relevant to the room, not a random expo hall.", icon: "🏬" },
          { title: "Recorded Sessions", desc: "Every talk is recorded, so you can catch what you missed after the event ends.", icon: "🎥" },
          { title: "Full Day Catering", desc: "Breakfast, lunch and coffee included, so you can focus on the day instead of logistics.", icon: "☕" },
        ],
      },
      timeline: {
        label: "THE DAY AT A GLANCE",
        heading: "How the day unfolds",
        items: [
          { title: "Doors Open & Registration", desc: "Check in, grab a badge and coffee before the opening keynote begins.", year: "8:30 AM" },
          { title: "Morning Keynotes", desc: "Three main-stage talks from industry leaders on where things are headed.", year: "9:30 AM" },
          { title: "Breakout Workshops", desc: "Choose from parallel hands-on sessions across three tracks.", year: "1:00 PM" },
          { title: "Closing Mixer", desc: "Wrap up the day with drinks, live music and open networking.", year: "5:30 PM" },
        ],
      },
      pricing: {
        label: "TICKETS",
        heading: "Choose your ticket",
        plans: [
          { plan: "General", price: "$149", desc: "Full access to all talks, workshops and the closing mixer.", features: ["All-day access", "Workshop entry", "Lunch included", "Session recordings"] },
          { plan: "VIP", price: "$349", desc: "Front-row seating plus a private speaker meet and greet.", features: ["Front-row seating", "Speaker meet & greet", "VIP lounge access", "Lunch included"] },
          { plan: "Group (5+)", price: "$119", period: "/person", desc: "Bring your team at a discounted group rate.", features: ["All-day access", "Workshop entry", "Lunch included", "Dedicated group check-in"] },
        ],
      },
      team: {
        label: "ORGANIZED BY",
        heading: "The team behind the event",
        items: [
          { name: "Naomi Park", title: "Event Director", bio: "Has produced industry gatherings for over a decade, from 50-person meetups to full-scale summits." },
          { name: "Diego Fernandez", title: "Program Lead", bio: "Curates the speaker lineup and workshop tracks to keep every session sharp and relevant." },
          { name: "Ines Novak", title: "Partnerships Lead", bio: "Handles sponsors and exhibitors, matching the right partners to the room." },
        ],
      },
      stats: [
        { num: "1,200+", label: "Attendees Last Year" },
        { num: "32", label: "Speakers & Workshops" },
        { num: "4.8", label: "Attendee Rating" },
        { num: "6th", label: "Annual Edition" },
      ],
      about: {
        label: "ABOUT THE EVENT",
        heading: "Built by organizers who attend, too",
        body1: "Convene Summit started as a single afternoon meetup in a shared office and has grown into a full-day gathering people plan their year around. We still run it the same way: content first, no filler sessions.",
        body2: "Every talk and workshop is chosen for what attendees can use the next morning. If a session would not hold our own attention, it does not make the schedule.",
      },
      testimonials: {
        label: "WHAT ATTENDEES SAY",
        heading: "Why people keep coming back",
        items: [
          { quote: "Best industry event I've been to this year. The workshops alone were worth the ticket price.", name: "Farhan Qureshi", role: "Product Manager" },
          { quote: "Well organized from start to finish, and the networking mixer led to two real partnerships for us.", name: "Hannah Sorensen", role: "Founder" },
          { quote: "The speaker lineup was sharper than most conferences twice the price. Already booked for next year.", name: "Miguel Torres", role: "Marketing Lead" },
        ],
      },
      faq: {
        label: "GOOD TO KNOW",
        heading: "Before you book your ticket",
        items: [
          { q: "Where is the event held?", a: "The summit takes place at the downtown convention center, a short walk from the main transit station." },
          { q: "Is there a virtual option?", a: "The main keynotes are livestreamed for ticket holders, though workshops are only available in person." },
          { q: "Can I get a refund?", a: "Tickets are fully refundable up to two weeks before the event and transferable at any time." },
          { q: "Is food included?", a: "Yes, breakfast, lunch and coffee throughout the day are included in every ticket type." },
        ],
      },
      cta: {
        heading: "Save your seat before tickets run out",
        sub: "Early tickets are limited and sell out most years. Reserve yours today.",
        button: "Get Tickets",
      },
      seo: {
        title: "Convene Summit – Talks, Workshops & Networking",
        description: "Join Convene Summit for a full day of expert talks, hands-on workshops and dedicated networking. Tickets are limited, reserve your seat today.",
      },
    },
  },

  {
    id: "general-nonprofit",
    name: "Nonprofit Organization",
    group: "community",
    archetype: "nonprofit",
    keywords: ["nonprofit", "non-profit", "ngo", "charity", "foundation", "trust", "nonprofit organization", "charitable organization", "cause", "donate", "volunteer organization", "community organization", "relief fund"],
    mood: ["warm", "soft", "clean"],
    images: "ngo",
    copy: {
      brand: "Clearwater Trust",
      label: "COMMUNITY-FUNDED, COMMUNITY-RUN",
      heading: "Small donations, real change, close to home",
      sub: "We work with local families and schools to close everyday gaps in food, learning and healthcare, one neighborhood at a time.",
      cta1: "Donate Now",
      cta2: "See Our Impact",
      offerings: {
        label: "WHERE YOUR SUPPORT GOES",
        heading: "How we put donations to work",
        sub: "Every program is run lean, with the vast majority of funds reaching the people we serve.",
        items: [
          { title: "Meal Programs", desc: "Weekly meal deliveries for families facing food insecurity across twelve neighborhoods.", icon: "🍲" },
          { title: "School Supplies", desc: "Backpacks, books and basic supplies distributed to students at the start of every term.", icon: "🎒" },
          { title: "Health Clinics", desc: "Free monthly clinics offering checkups, screenings and referrals for families without coverage.", icon: "🩺" },
          { title: "Tutoring Support", desc: "After-school tutoring run by trained volunteers for students who are falling behind.", icon: "📚" },
          { title: "Emergency Relief", desc: "Rapid-response grants for families facing sudden hardship, from rent to medical bills.", icon: "🆘" },
          { title: "Volunteer Network", desc: "A growing group of local volunteers who give their time to run programs each week.", icon: "🙋" },
        ],
      },
      pricing: {
        label: "WAYS TO GIVE",
        heading: "Choose how you'd like to help",
        plans: [
          { plan: "Monthly", price: "$25", period: "/month", desc: "Sustains a family's weekly meal box throughout the month.", features: ["Feeds one family weekly", "Impact email updates", "Cancel anytime"] },
          { plan: "Sponsor Student", price: "$60", period: "/month", desc: "Covers tutoring, supplies and meals for a student all year.", features: ["Full-year tutoring support", "School supplies included", "Progress updates"] },
          { plan: "One-Time Gift", price: "$100", desc: "A single gift directed to wherever the need is greatest.", features: ["Tax-deductible receipt", "Directed to urgent needs", "No commitment required"] },
        ],
      },
      stats: [
        { num: "$2.4M", label: "Raised Since 2015" },
        { num: "9,000+", label: "Families Supported" },
        { num: "420", label: "Active Volunteers" },
        { num: "91%", label: "Funds to Programs" },
      ],
      about: {
        label: "OUR MISSION",
        heading: "Support that starts with listening",
        body1: "Clearwater Trust began when a small group of neighbors started pooling grocery money for families going through a hard winter. That same instinct still guides every program we run.",
        body2: "We keep our team small and our overhead lower than most, so more of every dollar reaches the families and schools who need it. Every program is shaped by the community it serves.",
      },
      testimonials: {
        label: "STORIES FROM THE COMMUNITY",
        heading: "What our work means to people",
        items: [
          { quote: "The tutoring program helped my son catch up in reading. The volunteers genuinely cared about his progress.", name: "Marisol Reyes", role: "Parent" },
          { quote: "Clearwater's emergency grant covered our rent during a medical crisis. We would not have made it through without them.", name: "James Whitfield", role: "Program Recipient" },
          { quote: "As a partner school, their supply drives have meant every one of our students starts the year prepared.", name: "Dr. Amara Obi", role: "School Principal" },
        ],
      },
      faq: {
        label: "COMMON QUESTIONS",
        heading: "About giving and volunteering",
        items: [
          { q: "How much of my donation goes to programs?", a: "91 cents of every dollar donated goes directly to our programs. The rest covers essential operating costs." },
          { q: "Is my donation tax-deductible?", a: "Yes, Clearwater Trust is a registered nonprofit and all donations are tax-deductible to the extent allowed by law." },
          { q: "Can I volunteer without donating?", a: "Absolutely. Volunteers are just as valuable as donors, and we welcome help with programs, events and admin work." },
          { q: "Do you accept in-kind donations?", a: "Yes, we accept food, school supplies and other in-kind donations. Reach out and we'll coordinate a drop-off." },
        ],
      },
      cta: {
        heading: "Your support changes a family's week",
        sub: "Every donation, large or small, goes directly toward meals, supplies and care for local families.",
        button: "Donate Now",
      },
      seo: {
        title: "Clearwater Trust – Local Nonprofit & Community Fund",
        description: "Clearwater Trust runs meal, tutoring and health programs for local families. See our impact and donate or volunteer to support the community today.",
      },
    },
  },

  {
    id: "general-listing",
    name: "Listing Directory",
    group: "business",
    archetype: "listing",
    keywords: ["listing", "directory", "catalog", "marketplace", "rental", "listings site", "property listings", "classifieds", "browse listings", "rental marketplace", "directory site", "find a rental"],
    mood: ["clean", "corporate", "minimal"],
    images: "realestate",
    copy: {
      brand: "Harbor Listings",
      label: "BROWSE VERIFIED LISTINGS",
      heading: "Find the right listing, without the guesswork",
      sub: "A curated directory of verified listings with clear pricing, honest photos and details you can trust before you reach out.",
      cta1: "Browse Listings",
      cta2: "List With Us",
      offerings: {
        label: "WHY USE OUR DIRECTORY",
        heading: "Built to make browsing easy",
        sub: "Every listing is checked before it goes live, so what you see is what you get.",
        items: [
          { title: "Verified Listings", desc: "Every listing is reviewed by our team before publishing, with details checked against the source.", icon: "✅" },
          { title: "Powerful Filters", desc: "Narrow results by price, location, availability and features in a few clicks.", icon: "🔎" },
          { title: "Direct Contact", desc: "Message listing owners directly, with no middleman or extra booking fees.", icon: "💬" },
          { title: "Saved Searches", desc: "Save your filters and get notified the moment a matching listing goes live.", icon: "🔔" },
          { title: "Honest Photos", desc: "Listings must include recent, unedited photos so there are no surprises on arrival.", icon: "📷" },
          { title: "Easy Listing Tools", desc: "Owners can publish a new listing in minutes with our guided upload flow.", icon: "🧰" },
        ],
      },
      showcase: {
        label: "FEATURED LISTINGS",
        heading: "Popular listings this week",
        items: [
          { name: "Downtown Loft Studio", meta: "$1,450/mo", details: "1 bed, 1 bath, walk to transit, available now" },
          { name: "Riverside Two-Bedroom", meta: "$2,100/mo", details: "2 bed, 2 bath, in-unit laundry, pet friendly" },
          { name: "Cozy Garden Cottage", meta: "$980/mo", details: "Studio with private garden, available next month" },
          { name: "Uptown Family Home", meta: "$3,200/mo", details: "3 bed, 2 bath, garage, near schools" },
          { name: "Modern Micro Unit", meta: "$890/mo", details: "Compact studio, fully furnished, flexible lease" },
        ],
      },
      stats: [
        { num: "3,600+", label: "Active Listings" },
        { num: "98%", label: "Verified Listings" },
        { num: "45K+", label: "Monthly Visitors" },
        { num: "24 hrs", label: "Avg Response Time" },
      ],
      about: {
        label: "ABOUT THE DIRECTORY",
        heading: "A directory built on trust",
        body1: "Harbor Listings started after one too many disappointing visits to listings that looked nothing like their photos. We built a directory where every listing is checked before it goes live.",
        body2: "Today thousands of people browse Harbor Listings every month to find a place, book a rental or list their own space, knowing the details they see are accurate.",
      },
      testimonials: {
        label: "WHAT USERS SAY",
        heading: "Trusted by renters and owners alike",
        items: [
          { quote: "Every listing I clicked on matched the photos exactly. Found my apartment in under a week.", name: "Sana Malik", role: "Renter" },
          { quote: "Listing our property took ten minutes and we had our first serious inquiry within a day.", name: "Owen Fitzgerald", role: "Property Owner" },
          { quote: "The filters saved me hours. I could search by everything that actually mattered to me.", name: "Camille Rousseau", role: "Renter" },
        ],
      },
      faq: {
        label: "COMMON QUESTIONS",
        heading: "Before you browse or list",
        items: [
          { q: "Is it free to browse listings?", a: "Yes, browsing and contacting listing owners is completely free for anyone searching the directory." },
          { q: "How are listings verified?", a: "Our team reviews each listing's details and photos before it is published, and flags any that seem inaccurate." },
          { q: "How much does it cost to list?", a: "Basic listings are free. Featured placement and extra visibility are available as a paid upgrade." },
          { q: "Can I contact owners directly?", a: "Yes, every listing includes a direct message option so you can reach the owner without a middleman." },
        ],
      },
      cta: {
        heading: "Start browsing verified listings",
        sub: "New listings are added daily. Set up a saved search and we'll notify you of a match.",
        button: "Browse Listings",
      },
      seo: {
        title: "Harbor Listings – Browse Verified Rental Listings",
        description: "Search a curated directory of verified rental listings with honest photos and transparent pricing. Browse now or list your own space in minutes.",
      },
    },
  },

  {
    id: "general-education",
    name: "Education Academy",
    group: "education",
    archetype: "education",
    keywords: ["course", "classes", "academy", "institute", "training", "coaching", "online course", "learning center", "certification course", "skill training", "education center", "study program"],
    mood: ["clean", "corporate", "vibrant"],
    images: "course",
    copy: {
      brand: "Beacon Academy",
      label: "LEARN FROM PRACTICING EXPERTS",
      heading: "Build real skills, taught by people who use them",
      sub: "Structured courses and live coaching designed to take you from beginner to job-ready, with feedback at every step.",
      cta1: "Browse Courses",
      cta2: "Book Free Trial",
      offerings: {
        label: "WHY LEARN WITH US",
        heading: "A different way to learn",
        sub: "Small cohorts, real projects and instructors who are still working in the field.",
        items: [
          { title: "Live Cohort Classes", desc: "Join a small group of learners meeting live each week, not a pre-recorded course you watch alone.", icon: "🎓" },
          { title: "Practicing Instructors", desc: "Every instructor currently works in the field they teach, not just presents slides about it.", icon: "👩" },
          { title: "Project-Based Learning", desc: "Build a portfolio of real projects as you go, reviewed with detailed feedback each week.", icon: "🛠" },
          { title: "Flexible Schedules", desc: "Morning, evening and weekend batches, so class fits around your job or studies.", icon: "🗓" },
          { title: "Career Support", desc: "Resume reviews, mock interviews and referrals once you're ready to start applying.", icon: "💼" },
          { title: "Lifetime Access", desc: "Keep access to course materials and community long after your cohort ends.", icon: "♾" },
        ],
      },
      pricing: {
        label: "COURSE PLANS",
        heading: "Pick the path that fits your goal",
        plans: [
          { plan: "Self-Paced", price: "$149", desc: "Full course library with recorded lessons and project files.", features: ["All recorded lessons", "Downloadable projects", "Community forum access"] },
          { plan: "Live Cohort", price: "$499", desc: "Weekly live classes with an instructor and small peer group.", features: ["Weekly live sessions", "Instructor feedback", "Project reviews", "Certificate on completion"] },
          { plan: "1-on-1 Coaching", price: "$120", period: "/session", desc: "Personalized sessions focused on your goals and pace.", features: ["Custom curriculum", "Flexible scheduling", "Direct instructor access"] },
        ],
      },
      team: {
        label: "MEET YOUR INSTRUCTORS",
        heading: "Taught by people doing the work",
        items: [
          { name: "Dr. Samuel Okonkwo", title: "Lead Instructor, Data", bio: "Ten years working as a data analyst before moving into teaching full time." },
          { name: "Grace Lindholm", title: "Lead Instructor, Design", bio: "Design lead at two startups, now focused on training the next generation of designers." },
          { name: "Arjun Malhotra", title: "Career Coach", bio: "Runs resume and interview prep for every graduating cohort, drawing on years in tech hiring." },
        ],
      },
      stats: [
        { num: "8,500+", label: "Students Trained" },
        { num: "92%", label: "Course Completion" },
        { num: "4.8/5", label: "Average Rating" },
        { num: "120+", label: "Hiring Partners" },
      ],
      about: {
        label: "OUR APPROACH",
        heading: "Learning that looks like the real job",
        body1: "Beacon Academy was founded by instructors frustrated with courses that taught theory but never got students building. Every course here is structured around real projects, live feedback and a small enough class that no one falls behind.",
        body2: "We keep our instructor roster small and working, so what you learn reflects how the field actually operates today, not five years ago.",
      },
      testimonials: {
        label: "STUDENT STORIES",
        heading: "What our students say",
        items: [
          { quote: "The live feedback each week made all the difference. I built a portfolio I was actually proud to show employers.", name: "Wei Zhang", role: "Graduate, Data Track" },
          { quote: "Best course investment I've made. My instructor still answers questions months after the cohort ended.", name: "Fatima Al-Sayed", role: "Graduate, Design Track" },
          { quote: "Landed a job offer within six weeks of finishing, and the career coaching played a big part in that.", name: "Lucas Bergmann", role: "Graduate" },
        ],
      },
      faq: {
        label: "COMMON QUESTIONS",
        heading: "Before you enroll",
        items: [
          { q: "Do I need experience to start?", a: "No, most of our courses are designed for beginners and build up gradually with support along the way." },
          { q: "What if I miss a live class?", a: "Every session is recorded and available within 24 hours, so you can catch up on your own schedule." },
          { q: "Is there a certificate at the end?", a: "Yes, cohort and coaching students receive a certificate of completion once all projects are submitted." },
          { q: "Can I get a refund?", a: "Yes, we offer a full refund within the first two weeks of any cohort if it is not the right fit." },
        ],
      },
      cta: {
        heading: "Start learning something new today",
        sub: "Book a free trial class and see how a live cohort works before you commit.",
        button: "Book Free Trial",
      },
      seo: {
        title: "Beacon Academy – Live Courses Taught by Experts",
        description: "Learn job-ready skills through live cohort classes, real projects and career coaching. Browse courses or book a free trial class today.",
      },
    },
  },

  {
    id: "general-creator",
    name: "Content Creator",
    group: "creative",
    archetype: "creator",
    keywords: ["blog", "creator", "channel", "content", "vlog", "content creator", "blogger", "influencer", "youtube channel", "podcast host", "newsletter writer", "online creator"],
    mood: ["vibrant", "bold", "playful"],
    images: "blog",
    copy: {
      brand: "Nova Ray",
      label: "STORIES, GUIDES & EXTRAS",
      heading: "Hi, I'm Nova — welcome to my corner of the internet",
      sub: "I share honest stories, practical guides and behind-the-scenes moments with a growing community who keeps showing up.",
      cta1: "Watch Latest",
      cta2: "Join Newsletter",
      offerings: {
        label: "WHAT YOU'LL FIND HERE",
        heading: "A few things I make every week",
        sub: "New content lands every week across video, writing and a growing archive worth digging into.",
        items: [
          { title: "Weekly Videos", desc: "A new video every Thursday, covering whatever I'm learning, testing or figuring out that week.", icon: "🎥" },
          { title: "Behind the Scenes", desc: "Honest looks at the process, mistakes included, not just the polished final result.", icon: "🎬" },
          { title: "Written Guides", desc: "Longer step-by-step guides for readers who prefer to read at their own pace.", icon: "✍️" },
          { title: "Community Q&A", desc: "Monthly live sessions where I answer questions straight from the community.", icon: "💬" },
          { title: "Collabs & Features", desc: "Regular collaborations with other creators and guests I genuinely admire.", icon: "🤝" },
          { title: "Resource Library", desc: "Templates, tools and recommendations mentioned across videos, all in one place.", icon: "📂" },
        ],
      },
      showcase: {
        label: "POPULAR CONTENT",
        heading: "Where to start",
        items: [
          { name: "How I Actually Plan My Week", meta: "2.1M views", details: "My most-watched video, now a full written guide too" },
          { name: "Behind the Studio Setup", meta: "Series", details: "A four-part series on building a home studio on a budget" },
          { name: "Ask Me Anything: Live", meta: "Monthly", details: "A recurring live Q&A with the community" },
          { name: "One Year of Consistency", meta: "2024", details: "A personal essay on what changed after posting weekly" },
          { name: "Creator Toolkit Guide", meta: "Resource", details: "The exact tools used to plan and edit every video" },
        ],
      },
      stats: [
        { num: "850K+", label: "Subscribers" },
        { num: "3M+", label: "Monthly Views" },
        { num: "220+", label: "Videos Published" },
        { num: "40K+", label: "Newsletter Readers" },
      ],
      about: {
        label: "ABOUT ME",
        heading: "How this all started",
        body1: "I started posting videos as a way to document what I was learning, mostly for myself. A handful of people found the first few useful, and that handful slowly grew into a real community.",
        body2: "These days I post every week, write a newsletter twice a month and still answer as many comments as I can. Thanks for being here, genuinely.",
      },
      testimonials: {
        label: "WHAT THE COMMUNITY SAYS",
        heading: "Some kind words",
        items: [
          { quote: "Nova's guides are the only ones I actually finish. Clear, honest and never bloated with filler.", name: "Derek Osei", role: "Subscriber" },
          { quote: "The behind-the-scenes content is what keeps me coming back. Feels like a real person, not a brand.", name: "Isabelle Moreau", role: "Newsletter Reader" },
          { quote: "Collaborating on a video together was genuinely fun and the audience response was incredible.", name: "Theo Nakamura", role: "Fellow Creator" },
        ],
      },
      faq: {
        label: "QUESTIONS I GET A LOT",
        heading: "Frequently asked",
        items: [
          { q: "How often do you post?", a: "A new video goes up every Thursday, with a newsletter twice a month covering what didn't make the video." },
          { q: "Can I collaborate with you?", a: "Yes, I'm always open to collaborations. Send a message through the contact page with your idea." },
          { q: "Do you offer brand partnerships?", a: "I work with a small number of brands each year that genuinely fit the content. Details are on the contact page." },
          { q: "Where can I watch older videos?", a: "The full archive is linked in the resource library, organized by topic for easy browsing." },
        ],
      },
      cta: {
        heading: "Don't miss the next one",
        sub: "Join the newsletter for early access, extras and the occasional behind-the-scenes story.",
        button: "Join Newsletter",
      },
      seo: {
        title: "Nova Ray – Videos, Guides & Newsletter",
        description: "Join Nova Ray for weekly videos, honest behind-the-scenes stories and practical guides. Watch the latest video or subscribe to the newsletter.",
      },
    },
  },

  {
    id: "general-hotel",
    name: "Boutique Stay",
    group: "hospitality",
    archetype: "hotel",
    keywords: ["stay", "guesthouse", "rooms", "lodging", "accommodation", "hotel", "inn", "bed and breakfast", "place to stay", "boutique hotel", "overnight stay", "short stay"],
    mood: ["elegant", "warm", "soft"],
    images: "hotel",
    copy: {
      brand: "The Willow Inn",
      label: "A QUIET PLACE TO STAY",
      heading: "Rest well, right in the heart of town",
      sub: "Comfortable rooms, a warm welcome and a location close to everything worth seeing, without the noise of a big hotel.",
      cta1: "Check Availability",
      cta2: "View Rooms",
      offerings: {
        label: "WHY STAY WITH US",
        heading: "Everything you need, nothing you don't",
        sub: "Small enough to feel personal, well-located enough to explore easily.",
        items: [
          { title: "Comfortable Rooms", desc: "Quiet, freshly renovated rooms with real beds, blackout curtains and fast wifi.", icon: "🛏" },
          { title: "Central Location", desc: "A short walk from the old town, main sights and the best local restaurants.", icon: "📍" },
          { title: "Free Breakfast", desc: "A generous breakfast spread included with every stay, served until late morning.", icon: "🥐" },
          { title: "24-Hour Front Desk", desc: "Someone is always at the desk, whenever you arrive or need a hand.", icon: "🛎" },
          { title: "Flexible Check-In", desc: "Early check-in and late check-out available on request, based on availability.", icon: "🕐" },
          { title: "Local Recommendations", desc: "Our team shares the spots locals actually go, not just the tourist list.", icon: "🗺" },
        ],
      },
      showcase: {
        label: "OUR ROOMS",
        heading: "Choose your room",
        items: [
          { name: "Cozy Single Room", meta: "$89/night", details: "One queen bed, city view, breakfast included" },
          { name: "Classic Double Room", meta: "$119/night", details: "Two beds or one king, courtyard view, breakfast included" },
          { name: "Garden Suite", meta: "$169/night", details: "Separate sitting area, private garden access" },
          { name: "Family Room", meta: "$199/night", details: "Sleeps four, connecting layout, breakfast included" },
        ],
      },
      stats: [
        { num: "4.8", label: "Guest Rating" },
        { num: "22", label: "Rooms" },
        { num: "15K+", label: "Guests Hosted" },
        { num: "5 min", label: "Walk to Old Town" },
      ],
      about: {
        label: "OUR STORY",
        heading: "A family-run stay since 2011",
        body1: "The Willow Inn opened as a small six-room guesthouse and has grown slowly, one careful renovation at a time. We kept it small on purpose, so every guest still gets a personal welcome at the door.",
        body2: "Run by the same family since it opened, the inn blends the comfort of a proper hotel with the warmth of staying somewhere that knows your name by the second morning.",
      },
      testimonials: {
        label: "GUEST REVIEWS",
        heading: "What guests are saying",
        items: [
          { quote: "Quiet, spotless and the staff genuinely went out of their way to help us plan our days. Would stay again.", name: "Elena Petrova", role: "Guest" },
          { quote: "Best breakfast of our entire trip and the location made walking everywhere easy. Highly recommend.", name: "Noah Bergstrom", role: "Guest" },
          { quote: "Felt like staying with family. Small touches everywhere, from the welcome note to the local tips.", name: "Aditi Sharma", role: "Guest" },
        ],
      },
      faq: {
        label: "GOOD TO KNOW",
        heading: "Before you book",
        items: [
          { q: "What time is check-in?", a: "Standard check-in is from 2 PM and check-out is by 11 AM, with early or late options on request." },
          { q: "Is breakfast included?", a: "Yes, a full breakfast is included with every room rate and served until 10:30 AM daily." },
          { q: "Do you offer free cancellation?", a: "Most rates include free cancellation up to 48 hours before arrival. Details are shown at booking." },
          { q: "Is parking available?", a: "Limited on-site parking is available for a small daily fee, and street parking is nearby." },
        ],
      },
      cta: {
        heading: "Your room is waiting",
        sub: "Check availability for your dates and book directly for the best rate.",
        button: "Check Availability",
      },
      seo: {
        title: "The Willow Inn – Boutique Stay in the Heart of Town",
        description: "Comfortable rooms, free breakfast and a central location near the old town. Check availability and book your stay at The Willow Inn today.",
      },
    },
  },
];
